language: python
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install poetry
  - poetry install
script:
  - ./manage.py migrate
  - PYTHONWARNINGS=always coverage run manage.py test
  - flake8 .
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=jugemaj"
after_success:
  - coveralls
