language: python
dist: bionic
jobs:
  include:
    - python: 3.6
      env: DJANGO_LT=2.1
    - python: 3.7
      env: DJANGO_LT=2.2
    - python: 3.8
      env: DJANGO_LT=3.0
    - python: 3.8
install:
  - pip install poetry
  - poetry install
  - test -z "${DJANGO_LT}" || pip install -U "django<${DJANGO_LT}"
script:
  - ./manage.py migrate
  - PYTHONWARNINGS=always coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - mypy .
  - pydocstyle
  - test -n "${DJANGO_LT}" || safety check
  - sphinx-build docs build
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=jugemaj"
after_success:
  - coveralls
