# Generated by Django 3.0.6 on 2020-05-21 16:45

from django.db import migrations

import requests

QUERY = """
SELECT ?item ?itemLabel
WHERE
{
  ?item wdt:P31 wd:Q146.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],fr,en". }
}
"""


def get_all_cats(apps, schema_editor):
    WikiDataModel = apps.get_model("example", "WikiDataModel")
    prms = {'format': 'json', 'query': QUERY}
    req = requests.get('https://query.wikidata.org/sparql', params=prms)
    for result in req.json()['results']['bindings']:
        wikidata = int(result['item']['value'].split('/')[-1][1:])
        name = result['itemLabel']['value']
        WikiDataModel.objects.create(name=name, wikidata=wikidata)


def delete_all_cats(apps, schema_editor):
    WikiDataModel = apps.get_model("example", "WikiDataModel")
    WikiDataModel.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_all_cats, delete_all_cats),
    ]
