# Generated by Django 4.0 on 2021-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_elect_a_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidatamodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
