# Generated by Django 4.0 on 2021-12-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jugemaj", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.IntegerField(
                choices=[
                    (1, "Super"),
                    (2, "Bien"),
                    (3, "Ok"),
                    (4, "Passable"),
                    (5, "Insuffisant"),
                    (6, "Nul"),
                ],
                null=True,
                verbose_name="choix",
            ),
        ),
    ]
