name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.9]
        include:
          - python-version: 3.8
            django-lt: 3.1
          - python-version: 3.9
            django-lt: 5.0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U poetry
          poetry config virtualenvs.create false --local
          poetry install --no-interaction --no-ansi -E example
          test -z "${{ matrix.django-lt }}" || python -m pip install -U "django<${{ matrix.django-lt }}"
      - run: python -Wa ./manage.py migrate
      - run: PYTHONWARNINGS=always coverage run manage.py test
      - run: pip install "git+https://github.com/${GITHUB_REPOSITORY}.git#egg=django-jugemaj"

      - uses: codecov/codecov-action@v1
